spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/example
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    enabled: true
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0
logging:
  level:
    org:
      hibernate:
        type: error

