spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/example
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
logging:
  level:
    org:
      hibernate:
        type: error
